apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - prometheus-rbac.yaml
  - prometheus-configmap.yaml
  - prometheus-pvc.yaml
  - prometheus-deployment.yaml
  - prometheus-service.yaml
  - kube-state-metrics-rbac.yaml
  - kube-state-metrics-deployment.yaml
  - kube-state-metrics-service.yaml
  - node-exporter-daemonset.yaml
  - grafana-datasource-configmap.yaml
  - grafana-dashboard-provider-configmap.yaml
  - grafana-dashboards-configmap.yaml
  - grafana-pvc.yaml
  - grafana-deployment.yaml
  - grafana-service.yaml
  - headlamp-rbac.yaml
  - headlamp-deployment.yaml
  - headlamp-service.yaml
