apiVersion: v1
kind: Service
metadata:
  name: threat-intel-ai-service
  namespace: c4i
  labels:
    app: threat-intel-ai-service
spec:
  type: ClusterIP
  selector:
    app: threat-intel-ai-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
