apiVersion: v1
kind: Service
metadata:
  name: defense-api-gateway
  namespace: c4i
  labels:
    app: defense-api-gateway
spec:
  type: NodePort
  selector:
    app: defense-api-gateway
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 30081
      protocol: TCP
